package bbl;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import it.uniroma1.lcl.babelnet.BabelNet;
import it.uniroma1.lcl.jlt.util.Language;

public class BabelnetMain {
	public static void main(String[] args) {
		BabelUtil bu = new BabelUtil();
		bu.initAll();
		Object[] terms = bu.loadTermArray("/home/sumanta/Documents/eric_codes/terms_arr.json");//input term array generated by process_docs.py
		File file = new File("/home/sumanta/Documents/eric_codes/output/Babelnet_Main_result.txt");//output text file; input for TermParser
		bu.iterateArray(terms, file);
		System.out.println("Operation complete");
		
		/*BabelNet bn = BabelNet.getInstance();
		System.out.println(bn.getSynsets("apple", Language.EN));*/
	}
}
